#!/bin/bash

ggDockerDir="/Users/tiberiu/work/gg-docker/"

echo $1;
echo $2;

cd ${ggDockerDir};
echo ${PWD};

function docker-start {
    npm run start -- --build fe
    docker-compose up -d
}

if [ -z $1 ]; then
    docker-start
    exit 2
fi

while [ $# -ne 0 ]; do
    case "$1" in
        -u)
            git pull --rebase
            npm run start -- --build fe
            #gimme-aws-creds --profile prd
            #export AWS_DEFAULT_PROFILE=prd
            #aws ecr get-login-password | docker login --username AWS --password-stdin https://604083106117.dkr.ecr.eu-west-1.amazonaws.com
            docker-compose pull
            docker-compose up -d
            shift
            ;;
        -*)
            echo "Unknown option: $1" >&2
            exit 2
            ;;
        *)
            break
            ;;
    esac
done

echo -e ${input}
