#!/usr/bin/env bash


echo 'before running, insure git is installed, and arch boot-strapping script is in home directory'

echo ''

sudo pacman -S openssh

ssh-keygen -t ed25519

echo ' '
echo 'Add this public key to your github account before continueing'
echo ' '

cat ~ /.ssh/id_ed25519.pub

echo "

ready y

cd ~

mkdir Repo
cd Repo

# Pull down dot files from github

git clone git@github.com:ceaia-tiberiu/dotFiles.git dot

ln -s ~/Repo/dot/.bin ~/
ln -s ~/Repo/dot/.config ~/
ln -s ~/Repo/dot/.gitconfig ~/
ln -s ~/Repo/dot/.zshrc
ln -s ~/Repo/dot/.zshrc-personal

pacman -S base-devel

cd ~/.config
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
cd ~ 

#install applications
pacPackages=()

yayPackages=()

sudo pacman -s ${pacPackages[@]}
yay -s ${yayPackages[@]}
