#!/usr/bin/env bash

sudo pacman -Sy broadcom-wl-dkms blueman 

sudo rmmod b43
sudo rmmod ssd
sudo modprobe wl


echo "Now reboot your pc"

echo "in case this doesn't work use nmtui => gui for network manager works !!"
